server:
  port: 8081

spring:
  datasource:
    username: root
    password: zkvpfkxp12!@
    url: jdbc:mysql://localhost:3306/prj1?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
