#server:
#  port: 8081

spring:
  datasource:
    username: root
    password: 12341234
    url: jdbc:mysql://localhost:3306/project_01
    driver-class-name: com.mysql.cj.jdbc.Driver

redis:
  host: localhost
  port: 6379

jpa:
  database-platform:
  show-sql: true
  hibernate:
    ddl-auto: update

security:
  jwt:
    header: Authorization
    secret: 이것은시크릿키야아아아아
    token-validity-in-seconds: 604800


mvc:
  pathmatch:
    matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
