#server:
#  port: 8081

spring:
  datasource:
    username: root
    password: 12341234
    url: jdbc:mysql://localhost:3306/project_01
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  database-platform:
  show-sql: true
  hibernate:
    ddl-auto: update
